import { TypeOrmModule } from '@nestjs/typeorm';
import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { User } from 'src/users/user.entity';

@Entity()
export class Report {
  @PrimaryGeneratedColumn() // auto generated by typeORM
  id: number;
  @Column({ default: false }) // default is false so admins can approve
  approved: boolean;

  @Column()
  make: string;
  @Column()
  model: string;
  @Column()
  year: number;
  @Column()
  mileage: number;
  @Column()
  longitude: number;
  @Column()
  latitude: number;

  @Column()
  price: number;
  @ManyToOne(() => User, (user) => user.reports) // need to memorize the syntax to make one to many relationship
  user: User;
}
