import { TypeOrmModule } from '@nestjs/typeorm';
import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { User } from 'src/users/user.entity';

@Entity()
export class Report {
  @PrimaryGeneratedColumn() // auto generated by typeORM
  id: number;

  @Column()
  make: string;
  @Column()
  model: string;
  @Column()
  year: number;
  @Column()
  mileage: number;
  @Column()
  longitude: number;
  @Column()
  latitude: number;

  @Column()
  price: number;
  @ManyToOne()
  user: User;
}
