### CREATE REPORT
POST http://localhost:3000/reports HTTP/1.1
Content-Type: application/json

{
"make": "subaru",
"model": "impreza",
"year": 2009,

"longitude": 0,
"latitude": 0,
"mileage": 50000,
"price": 100
}
### Get one report
GET http://localhost:3000/reports/9 HTTP/1.1

###Get estimate price

GET http://localhost:3000/reports?make=ford&model=good&year=2020&longitude=55.88&latitude=66.6&mileage=550 HTTP/1.1

###Delete report
DELETE http://localhost:3000/reports/4 HTTP/1.1
###Approve report
PATCH http://localhost:3000/reports/10 HTTP/1.1
Content-Type: application/json

{
"approved":true
}
